---

x-cardano-node: &cardano-node
  image: ghcr.io/intersectmbo/cardano-node:latest
  environment:
    CARDANO_BLOCK_PRODUCER: true
  command: >
    run --topology /configs/configs/topology.json
      --config /configs/configs/config.json
      --database-path /state
      --socket-path /state/node.socket
      --tracer-socket-path-connect /tracer/tracer.socket
      --shelley-operational-certificate /configs/keys/opcert.cert
      --shelley-kes-key /configs/keys/kes.skey
      --shelley-vrf-key /configs/keys/vrf.skey
      --port 3001
      --host-addr 0.0.0.0
      +RTS -N -A16m -qg -qb -RTS
  depends_on:
      configurator:
        condition: service_completed_successfully

x-tracer: &tracer
  image: paolino/antithesis-tracer:latest
  restart: on-failure
  build:
    context: "../../tracer/"
    # ideally we would like to use a precompiled version of the tracer
    # but unfortunately it's not yet packaged in archives
    # https://github.com/IntersectMBO/cardano-node/issues/6228
    dockerfile: "Dockerfile.compiled"
    args:
      CARDANO_NODE_VERSION: "main"

services:
  configurator:
    image: ${registry}${testnet}_configurator:latest
    container_name: configurator
    volumes:
      - p1-configs:/configs/1
      - p2-configs:/configs/2
      - p3-configs:/configs/3
      - p4-configs:/configs/4
      - p5-configs:/configs/5
    build:
      context: "."
      dockerfile: "Dockerfile.configurator"

  tracer:
    <<: *tracer
    hostname: tracer.example
    container_name: tracer
    volumes:
      - tracer:/opt/cardano-tracer
    command:
       - "--config"
       - "tracer-config.yaml"

  p1:
    <<: *cardano-node
    container_name: p1
    hostname: p1.example
    volumes:
      - p1-configs:/configs
      - p1-state:/state
      - tracer:/tracer
  p2:
    <<: *cardano-node
    container_name: p2
    hostname: p2.example
    volumes:
      - p2-configs:/configs
      - p2-state:/state
      - tracer:/tracer
  p3:
    <<: *cardano-node
    container_name: p3
    hostname: p3.example
    volumes:
      - p3-configs:/configs
      - p3-state:/state
      - tracer:/tracer

  p4:
    <<: *cardano-node
    container_name: p4
    hostname: p4.example
    volumes:
      - p4-configs:/configs
      - p4-state:/state
      - tracer:/tracer

  p5:
    <<: *cardano-node
    container_name: p5
    hostname: p5.example
    volumes:
      - p5-configs:/configs
      - p5-state:/state
      - tracer:/tracer
  s1:
    image: paolino/antithesis-sidecar:latest
    restart: on-failure
    container_name: s1
    hostname: s1.example
    environment:
      POOLS: "5" # FIXME: could remove

  tracer-sidecar:
    image: paolino/antithesis-tracer-sidecar:latest
    restart: on-failure
    container_name: tracer-sidecar
    hostname: tracer-sidecar.example
    environment:
      POOLS: "5"
    volumes:
      - tracer:/opt/cardano-tracer

volumes:
  tracer:
  p1-state:
  p2-state:
  p3-state:
  p4-state:
  p5-state:
  p1-configs:
  p2-configs:
  p3-configs:
  p4-configs:
  p5-configs:
